FROM node:22.7.0-slim AS builder
WORKDIR /front
COPY . /front
RUN npm install -y
RUN npm install -g @angular/cli -y
RUN ng build --configuration=production --base-href=/engine/

FROM nginx:1.17.6-alpine
RUN rm -r /usr/share/nginx/html/
COPY --from="builder" /front/dist/minimal2d-game-engine-ui/browser/ /usr/share/nginx/html/
CMD ["/bin/sh",  "-c",  "exec nginx -g 'daemon off;'"]
