services:
  minimal-2d-game-engine-api:
    container_name: minimal-2d-game-engine-api
    image: minimal-2d-game-engine-api:latest
    build:
      context: minimal-2d-game-engine-api
    ports:
      - "8080:8080"
    volumes: 
      - ./minimal-2d-game-engine/:/minimal-2d-game-engine/
      - ./workspace/:/workspace/
    networks: 
      - minimal-2d-game-engine-net
  minimal-2d-game-engine-ui:
    container_name: minimal-2d-game-engine-ui
    image: minimal-2d-game-engine-ui:latest
    build:
      context: minimal2d-game-engine-ui
    ports:
      - "81:80"
    networks: 
      - minimal-2d-game-engine-net

networks: 
    minimal-2d-game-engine-net:
