spring:
  application:
    name: minimal-2d-game-engine-api

engine:
  path: /Users/tronxi/workspace/minimal-2d-game-engine/minimal-2d-game-engine/
  workspace: /Users/tronxi/workspace/minimal-2d-game-engine/workspace/
  custom-elements-package: src/main/java/dev/tronxi/engine/elements/custom
  custom-elements-package-name: dev.tronxi.engine.elements.custom.
  levels-directory: levels

