spring:
  application:
    name: minimal-2d-game-engine-api

engine:
  version: 1.0-SNAPSHOT
  path: /minimal-2d-game-engine/
  workspace: /workspace/
  custom-elements-package: src/main/java/dev/tronxi/engine/elements/custom
  custom-elements-package-name: dev.tronxi.engine.elements.custom.
  levels-directory: src/main/resources/levels
  properties-path: src/main/resources/engine.properties
  jar-directory: target

